### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by dtorner** [JakeLane/Toffeed#25]
Coul you add localization to the app?,if you are kind to do it, I'll translate it to Spanish for free :-D

**Comment by JakeLane** [comment]
That would be awesome if you would! I'm really busy at the moment with university at the moment unfortunately so I'll try to get to it as soon as I can.

**Comment by dtorner** [comment]
Sure, take your time, university and family goes first in the list :-)

On jue., mar. 10, 2016 at 10:07 a. m., Jake Lane < notifications@github.com [notifications@github.com] > wrote:
That would be awesome if you would! I'm really busy at the moment with
university at the moment unfortunately so I'll try to get to it as soon as I
can.

—
Reply to this email directly or view it on GitHub
[https://github.com/JakeLane/Toffeed/issues/25#issuecomment-194744989] .[https://github.com/notifications/beacon/ALQhrab77C1WAU2IGZwe9l6y6Ls8R0hMks5pr98wgaJpZM4Hq3Zy.gif]

**Comment by JakeLane** [comment]
The app should be prepared for localisation. If you're still interested in providing translations, I've put together a page [here](/JakeLane/Toffeed/wiki/Localisation) with some instructions. Thanks again!

**Comment by Coyoter** [comment]
I can help translate Chinese (Simplified Chinese and Traditional Chinese).

**Comment by JakeLane** [comment]
That would be great! If you wish to do any translations, please follow the instructions [here](https://github.com/JakeLane/Toffeed/wiki/Localisation).

**Comment by Coyoter** [comment]
I have mailed to you, check your email box : ) 

Traditional Chinese (Hong Kong, Taiwan etc) and Simplified Chinese (China).

**Comment by JakeLane** [comment]
Thanks @Coyoter!

I'm gonna close this now. If you would like a language added or are interested in providing translations, please create a separate issue.
