### ISSUE TITLE
Save picture 

### ISSUE THREAD

**Issue by Dribfunk** [JakeLane/Toffeed#30]
I was hoping you could find a way to enable the saving of photos on the app straight to the phone. 

That aside, I'm loving your work!

**Comment by JakeLane** [comment]
Will do, this is a common request.

**Comment by JakeLane** [comment]
Implemented in d9ae7328d9a8f41d5c9afb4f8f01752472637805.

**Comment by Dribfunk** [comment]
Thanks - but what should I do now??

**Comment by JakeLane** [comment]
You'll be able to long press images to save them in the next release.
