### ISSUE TITLE
Marshmallow Crash

### ISSUE THREAD

**Issue by creativetrendsapps** [JakeLane/Toffeed#33]
Trying to save an image or share an image crashes the app unless the user grants permission to write or read storage in Marshmallow manually. As a suggestion to fix this crash I'd suggest add runtime permissions.

**Comment by creativetrendsapps** [comment]
Using this library fixed the issue for me: https://github.com/greysonp/permiso

**Comment by Coyoter** [comment]
My friend using HTC M9 with Mashmallow also Crash too. It's happened when they upgrade Toffeed to 1.5.0 later.

But my Samsung S6 edge is working fine.

**Comment by JakeLane** [comment]
Thanks for the report, I feel pretty dumb for forgetting about Marshmallow permissions.
