### ISSUE TITLE
Copy & Paste Broken

### ISSUE THREAD

**Issue by creativetrendsapps** [JakeLane/Toffeed#35]
Since including the long press context menu, you can no longer long press to get the copy/paste long press context menu.

**Comment by creativetrendsapps** [comment]
Fixed by removing the webView long click listener. Also moved the registerContextMenu to the OnResume state of the webView.

**Comment by JakeLane** [comment]
Thanks for the report, didn't realise that happened. Will try to fix when I get the chance.
