### ISSUE TITLE
About "MostRecent" and "TopStories" newsfeed

### ISSUE THREAD

**Issue by ghost** [JakeLane/Toffeed#36]
Hello JakeLane, I am here to suggest you to change a few things about "Most recent" and "Top Stories" newsfeed.

---

Today your app is like that: http://i.imgur.com/deirzFa.png
1)The "Most Recent" button is not visible in the draw. 
So we have to click on "Main Menu" button (that redirects to https://m.facebook.com/home.php?soft=bookmarks) and then search for "Most Recent" option in the FB webpage.

2)After it, if we want to see "Top Stories" Newsfeed again, we need to click on "News Feed" button in the draw.
But there is a problem: 
It not opens "Top Stories" newsfeed, it continues opening "Most Recent" NewsFeed. As you can see in this print:  http://i.imgur.com/8Cdngdi.png
So we need manually click in "Top Stories" option in NewsFeed: http://i.imgur.com/GOjIbHw.png

So after that, it opens "Top Stories" NewsFeed again: http://i.imgur.com/Eo660xe.png

---

My suggestion to solve all these annoying problems:
1) Add a "Most Recent" button in the draw: http://i.imgur.com/Um4r2F2.png But this button should not be visible as default. 
It should be in the draw, only if the user goes to "Settings" in the app and then activate it. Exactly as it happens with "Back button" in the settings.
This "Most Recent" button should redirect to https://m.facebook.com/home.php?sk=h_chr

2) And now how to solve the second problem?
It's simple. The "News Feed" button should redirect to https://m.facebook.com/home.php?sk=h_nor 

Today this "News Feed" button redirects to https://m.facebook.com/home.php or https://m.facebook.com/  (I don't know which of the two you chose, but I'm sure it's one of these two).
But these two links don't force the FB page to open in "Most Recent" or "TopStories" mode. They simply obey a previous order. 
So you can only force the FB webpage to open in "Most Recent" adding ?sk=h_chr in the link or open "Top Stories" adding ?sk=h_nor in the link.

---

I hope I have been helpful.

Best Regards,
John Michael.

**Comment by JakeLane** [comment]
The button I had before used those url parameters but I had trouble keeping the visibility on the page consistent.

Putting it in the Navigation Bar has been requested a few times, so I think it's definitely worth implementing.
