### ISSUE TITLE
Try to hide information about birthdays in Newsfeed

### ISSUE THREAD

**Issue by ghost** [JakeLane/Toffeed#39]
Hello again Jake, 
Please try to hide information about birthdays in Newsfeed, as you can see here: http://i.imgur.com/uijqSNN.png

I don't know if it possible, but if you can hide Sponsored posts, Birthdays posts should be easy :P   

Thank you for you attention!

**Comment by JakeLane** [comment]
Implemented in 42dfa41c68049ab28c0fb67a2fca4fdae950d9ef. Should be in the next full release (not the coming bugfix).
