### ISSUE TITLE
Cover photo

### ISSUE THREAD

**Issue by creativetrendsapps** [JakeLane/Toffeed#4]
This app is great. Besides the profile image, is it possible to add a users cover photo in the navigation drawer?

**Comment by JakeLane** [comment]
With the current code structure, not really. However I am considering adding OAuth login to allow more features to be added and cover photos would be trivial with access to the Facebook API.

**Comment by creativetrendsapps** [comment]
Understandable. Great app nonetheless!

**Comment by JakeLane** [comment]
Implemented in 10e4a1533cde12d93f191b6b5670e16a53cd8360
