### ISSUE TITLE
Suggestion to add an in-browser

### ISSUE THREAD

**Issue by ghost** [JakeLane/Toffeed#46]
Hello JakeLane, I suggest you to add an in-browser in the Toffed apk.

Maybe this browser should be powered by Android WebView, but it should be optional.

1)If the user wants to (continue) use another browser to open FB links (like Chrome, Firefox, ...), he can do it.
2)If the user wants an in-browser to open FB links, he can do it too.

*With the possibility to change for one or another option.

Thank you for your attention.

**Comment by creativetrendsapps** [comment]
Toffeed has Chrome Custom Tabs.

**Comment by ghost** [comment]
Really? So I am sorry, because here it continues to open links in Chrome. :(

**Comment by creativetrendsapps** [comment]
You most likely need to update your version of Chrome. Unless @JakeLane
changed something.

**Comment by JakeLane** [comment]
All external links are put through the Chrome Custom tabs pipeline. An in-app browser would be quite difficult to implement well so the custom tabs are a good alternative.

Please reopen if you are still having issues with custom tabs. Note that you must have [Chrome](https://play.google.com/store/apps/details?id=com.android.chrome&hl=en) 45 or newer  for it to work.
