### ISSUE TITLE
Option to show a custom bar like the Facebook bar.

### ISSUE THREAD

**Issue by tdkl** [JakeLane/Toffeed#49]
Navigating via the navigation drawer gets annoying, since you have to open in all the time to get to the different sections. Since Facebook bar is disabled, how about implementing one? Maybe using an API like YouTube has at the top for tabs. 

Your app is the fastest one among all the wrappers and you have messenger working with spoofing the desktop site.

**Comment by JakeLane** [comment]
I added an option to enable the existing Facebook menu bar in the settings (9bce088b1dbce0f17060fd6246b9ddd90d2cd2d9).

**Comment by tdkl** [comment]
Thank you ☺ When will the build with it be released to the Play Store?
