### ISSUE TITLE
Login not working

### ISSUE THREAD

**Issue by pharidali** [JakeLane/Toffeed#54]
when i try to login
Not Logged In: You are not logged in. please login and try again. 

please help me to remove above issue.

Thank you

**Comment by RoneyThomas** [comment]
Could you try deleting the app data and cache. Then try opening it. You should be able to login.

**Comment by pharidali** [comment]
I tried but still got same

**Comment by pharidali** [comment]
i think their is problem on facebook app id

how to generate facebook app id with setting?

**Comment by pharidali** [comment]
Got It.

**Comment by JakeLane** [comment]
I'm glad you've got it working but for the reader's reference, if you make a fork you need to create a Facebook app at the [developer dashboard](https://developers.facebook.com/products/sharing/).
