### ISSUE TITLE
Please add admob ads. 

### ISSUE THREAD

**Issue by pharidali** [JakeLane/Toffeed#55]
Hey Buddy.

Please Add admob Banner Ads On The Footer of the Every Page. 

Mean Below Of The Every Web View.

**Comment by creativetrendsapps** [comment]
If you're using the source code (since it is open source) why not just add it yourself? I'm sure @JakeLane , doesn't want to add ads to the version on the Play Store.

**Comment by JakeLane** [comment]
You are welcome to create your own fork of the app, but I unfortunately have too little time to provide support.
