### ISSUE TITLE
Copyright violation

### ISSUE THREAD

**Issue by Poussinou** [JakeLane/Toffeed#59]
Hi @JakeLane 

I found [this app](https://play.google.com/store/apps/details?id=com.comunicacionesjg.facebook.mini), [this one](https://play.google.com/store/apps/details?id=dev.alshikh.lovable) and also [this one](https://play.google.com/store/apps/details?id=com.gomezgutierrezd.facebook.mini) on the Google Play Store. This guys just took your source code, most of them added some ads in it and put it on the Store, without warning this is free software or linking nor publishing the source code...

As you are the owner of the source code, feel free to open a request to google [here](https://support.google.com/legal/contact/lr_dmca?product=googleplay) to remove the false app from the Store, if it's your wish ;)

Don't forget to tell Google that:

* The app is licensed under MIT license and this guys are violating it;
* They are falsely claiming they made the app;
* Provide a link to this repo;
* Provide screenshots of your own app.

**Comment by JakeLane** [comment]
Thanks man, I really appreciate you bringing this to my attention.

I don't have any issues with people maintaining a fork especially as I no longer have the time to maintain my build of the app, but they should attributing correctly. I'll check some of them out and perhaps make a few takedown requests.

**Comment by Poussinou** [comment]
I don't think they're maintaining a fork, I rather think they just stole your work, it's something very common concerning free-and-open-source apps.
If you don't have too much time, I can fill the takedown requests and follow them, just ask ;)

**Comment by JakeLane** [comment]
Yeah, no doubt. From what I've seen so far, there are one or two maintained forks but far more copies with ads. I'll contact the developers which are maintaining forks without proper attribution and send takedown requests to copies. #55 makes a bit more sense now (and is pretty damn on the nose).

I think the GNU GPLv3 licence would have been far more suitable for this project, as that would have required source code to be available for each fork. MIT appears to allow duplicate apps under the condition that attribution and licence are provided unless I am misunderstanding my recourse?

**Comment by JakeLane** [comment]
I've now found over 10 apps which are derived from Toffeed which either have little or in most cases, no attribution. At this stage, I'm only going to email them to ask them to comply with the MIT licence terms. If they do not, I will most definitely send takedowns.

Thanks again for bringing this to my attention. I had no idea this was so rampant. Quite disappointed people would take advantage of my good faith. One of the apps I found has over 500,000 downloads, has no attribution at all, and contains ads.

**Comment by Poussinou** [comment]
I have nothing against the forks that improve an app, but I hate copies... I agree wih your point of vue, and do not hesitate to send the takedown requests :)

GNU GPL v3 is always the best solution when you want a strong copyleft license. It allows real forks, but make it very hard for copycats to steal your hardwork... So much open-source apps are stolen on the Play Store actually...

As you can see on my github profile, I'm tracking copyright violations. It would be great if you could give me all the links to the copies you found, so I could monitor the fake developers.
I've a more aggressive approach than you. I found new copies of open-source apps nearly everyday on the Play Store (have a look [here](https://github.com/physphil/UnitConverterUltimate/issues/86) for example). In my opinion, it's better to fill the DMCA takedown request as fast as you can, do not forget that this fake developpers are just stealers, and they know what they are doing when they steal your source code... But choice is yours...

**Comment by JakeLane** [comment]
I'll most definitely use GNU GPLv3 in the future. I've collated the ones I've found so far, there are likely more out there that I have missed.

| Name | Licence Violation | Copy? | Ads? |
| --- | --- | --- | --- |
| [Messenger for Facebook Lite](http://archive.is/cBtgH) | No attribution or licence | Reasonable changes | Yes |
| [CoolSocial](https://archive.is/VrUKw) | Attribution, no licence, provided my email address (violates liability) | Only colour changes | Yes |
| [Lovable For Facebook](https://archive.is/WC3yQ) | Attribution, no licence | Only colour changes | Yes |
| Mini for Facebook ([1](https://archive.is/1xDxX) and [2](https://archive.is/raXXj)) | No attribution or licence (mentioned Toffeed in description) | Only colour changes | No |
| [Mini Messenger - Lite Messenger](https://archive.is/v5xWq) | No attribution or licence | Reasonable changes | Yes |
| [Lite Messenger for Facebook](https://archive.is/cXnJo) | No attribution or licence | Reasonable changes | Yes |

**Comment by Poussinou** [comment]
Hum, have a look a [this repo](https://github.com/MaTriXy/FolioforFacebook) and read the README.md... Looks like your app as been used to build it.

EDIT: Some developers of the copies of Toffeed also copied others apps, I'm currently reporting them.

**Comment by creativetrendsapps** [comment]
@Poussinou the last repo you posted was my old code. In that repo, Toffeed is mentioned and in the code, there is credit given strings.

https://github.com/MaTriXy/FolioforFacebook/blob/master/app/src/main/res/values/strings.xml#L576 with the original name of the app "Facebook Wrapper". Also, each app that was used in Folio for Facebook, I've contributed back code, just for clarification.

**Comment by Poussinou** [comment]
@creativetrendsapps I have nothing against your own source code and app, since you complain with the free and open-source license :) Such forks aren't a problem for me, that's what open-source is done for!

So it looks like it's your own source code who's stolen by many fake "developers"... Do you want to help me to take them down?

**Comment by creativetrendsapps** [comment]
@Poussinou I actually don't own the Folio anymore. The "Friendly" for Facebook people do though they're in violation of many open source projects source code.

**Comment by Poussinou** [comment]
This apps have been removed. Please report here if you find other copies in the future 👍
